/**
 * generate-gap-report — Supabase Edge Function
 *
 * Accepts { firstName, scores, email? } and returns { report } generated by Claude.
 * If email is provided, sends a confirmation email via Resend (fire-and-forget).
 * Prompts are owned server-side; callers supply only data, not instructions.
 *
 * POST /functions/v1/generate-gap-report
 * Body:  { firstName: string, scores: { overall, relationships, identity, wealth, health, variant }, email?: string }
 * 200:   { report: string }
 */
const CORS = {
  "Access-Control-Allow-Origin":  "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};
const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS, "Content-Type": "application/json" },
  });

const PILLAR_LABELS: Record<string, string> = {
  relationships: "Relationships",
  identity:      "Identity Anchor",
  wealth:        "Wealth",
  health:        "Health",
};

function pillarRank(scores: Record<string, number>): { highest: string; lowest: string } {
  const keys = ["relationships", "identity", "wealth", "health"];
  const sorted = keys.sort((a, b) => scores[b] - scores[a]);
  return { highest: PILLAR_LABELS[sorted[0]], lowest: PILLAR_LABELS[sorted[sorted.length - 1]] };
}

function fmt(n: number): string {
  return Number(n).toFixed(1);
}

function buildSystemPrompt(variant?: string): string {
  const audience =
    variant === "male"   ? "high-achieving professional men" :
    variant === "female" ? "high-achieving professional women" :
    "high-achieving professionals";
  return `You are a diagnostic writer for 5 Years From Here, a premium identity \
development coaching platform for ${audience}. \
Write a short Gap Assessment report under 250 words. Tone: smooth, \
diagnostic, premium, conversational, encouraging. No markdown, no \
bullet lists, no headers. Plain prose paragraphs only. Five paragraphs max. \
Address the client directly by name and with "you" throughout — never use \
third-person pronouns (he, him, his, she, her, hers) anywhere in the report.`;
}

async function sendConfirmationEmail(
  resendKey: string,
  firstName: string,
  email: string,
  overallScore: number
): Promise<void> {
  const scoreLabel =
    overallScore >= 8.5 ? "High Alignment" :
    overallScore >= 7   ? "Strong Foundation" :
    overallScore >= 4   ? "Moderate Alignment" : "Critical Gap";

  const html = `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#0B0910;font-family:'DM Sans',system-ui,sans-serif;">
  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0B0910;padding:48px 24px;">
    <tr><td align="center">
      <table width="100%" style="max-width:560px;">
        <tr><td style="padding-bottom:32px;">
          <p style="margin:0;font-size:11px;letter-spacing:0.2em;text-transform:uppercase;color:rgba(237,233,244,0.4);">5 Years From Here</p>
        </td></tr>
        <tr><td style="padding-bottom:24px;border-bottom:1px solid rgba(255,255,255,0.07);">
          <h1 style="margin:0;font-family:Georgia,serif;font-size:28px;font-weight:300;color:#EDE9F4;line-height:1.2;">
            ${firstName.charAt(0).toUpperCase() + firstName.slice(1)}, your Gap Assessment is ready.
          </h1>
        </td></tr>
        <tr><td style="padding:28px 0;">
          <p style="margin:0 0 16px;font-size:14px;color:rgba(237,233,244,0.7);line-height:1.75;">
            Your overall score came in at <strong style="color:#C084FC;">${fmt(overallScore)} / 10</strong> — ${scoreLabel}.
            Your full report is waiting for you in the browser tab where you completed the assessment.
          </p>
          <p style="margin:0 0 28px;font-size:14px;color:rgba(237,233,244,0.7);line-height:1.75;">
            If you want to go deeper — the $49 diagnostic maps exactly where your operating system
            is leaking time, energy, focus, and leverage.
          </p>
          <a href="https://5yearsfromhere.com/diagnostic"
             style="display:inline-block;background:linear-gradient(135deg,#C084FC,#E879A0);border-radius:6px;
                    color:#fff;font-size:13px;font-weight:500;letter-spacing:0.06em;padding:14px 28px;
                    text-decoration:none;">
            Get the $49 Diagnostic →
          </a>
        </td></tr>
        <tr><td style="padding-top:24px;border-top:1px solid rgba(255,255,255,0.07);">
          <p style="margin:0;font-size:11px;color:rgba(237,233,244,0.25);line-height:1.6;">
            You're receiving this because you completed the Five-Year Gap Assessment at 5yearsfromhere.com.<br>
            © 5 Years From Here · Private diagnostic · Not for distribution.
          </p>
        </td></tr>
      </table>
    </td></tr>
  </table>
</body>
</html>`;

  await fetch("https://api.resend.com/emails", {
    method: "POST",
    headers: {
      "Content-Type":  "application/json",
      "Authorization": `Bearer ${resendKey}`,
    },
    body: JSON.stringify({
      from:    "5 Years From Here <hello@5yearsfromhere.com>",
      to:      [email],
      subject: `${firstName.charAt(0).toUpperCase() + firstName.slice(1)}, your Five-Year Gap Assessment`,
      html,
    }),
  });
}

Deno.serve(async (req: Request) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: CORS });
  if (req.method !== "POST")    return json({ error: "Method not allowed" }, 405);

  let body: { firstName?: string; scores?: Record<string, number> & { variant?: string }; email?: string };
  try {
    body = await req.json();
  } catch {
    return json({ error: "Invalid JSON body" }, 400);
  }

  const { firstName, scores, email } = body;
  if (!firstName || !scores) {
    return json({ error: "firstName and scores are required" }, 400);
  }

  const { highest, lowest } = pillarRank({ ...scores });
  const userPrompt = `Write a personalized Gap Assessment for ${firstName}.
Scores out of 10 — Overall: ${fmt(scores.overall)}, Relationships: ${fmt(scores.relationships)}, \
Identity Anchor: ${fmt(scores.identity)}, Wealth: ${fmt(scores.wealth)}, Health: ${fmt(scores.health)}.
Strongest pillar: ${highest}.
Lowest pillar: ${lowest}.
Structure: opening affirmation, gap diagnosis, pillar interpretation, \
identity anchor insight, one clear next-step focus area.
End with one forward-looking sentence. Under 250 words.`;

  const apiKey = Deno.env.get("ANTHROPIC_API_KEY");
  if (!apiKey) return json({ error: "ANTHROPIC_API_KEY not configured" }, 500);

  const res = await fetch("https://api.anthropic.com/v1/messages", {
    method: "POST",
    headers: {
      "Content-Type":      "application/json",
      "x-api-key":         apiKey,
      "anthropic-version": "2023-06-01",
    },
    body: JSON.stringify({
      model:      "claude-sonnet-4-6",
      max_tokens: 600,
      system:     buildSystemPrompt(scores.variant),
      messages:   [{ role: "user", content: userPrompt }],
    }),
  });

  if (!res.ok) {
    const err = await res.text();
    return json({ error: `Anthropic API error: ${res.status}`, detail: err }, 502);
  }

  const data   = await res.json();
  const report = data.content?.[0]?.text ?? "";

  // Fire-and-forget confirmation email — never blocks or fails the report response
  if (email) {
    const resendKey = Deno.env.get("RESEND_API_KEY");
    if (resendKey) {
      sendConfirmationEmail(resendKey, firstName, email, scores.overall).catch((err) =>
        console.error("[generate-gap-report] Resend error:", err)
      );
    }
  }

  return json({ report });
});
